version: "3.7"
services:
  influxdb:
    image: influxdb:1.8-alpine
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=rum_data
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminadmin
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=useruser
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning
volumes:
  influxdb_data: {}
  grafana_data: {}